fix a bug caused by h2 new version
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcIngredientRepository' defined in file [/Users/haozhan/code/l_SpringInAction5th/taco-cloud/target/classes/com/example/tacocloud/data/JdbcIngredientRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #5 of URL [file:/Users/haozhan/code/l_SpringInAction5th/taco-cloud/target/classes/schema.sql]: alter table Taco_Ingredients add foreign key (ingredient) references Ingredient(id); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Constraint "PRIMARY KEY | UNIQUE (ID)" not found; SQL statement:
alter table Taco_Ingredients add foreign key (ingredient) references Ingredient(id) [90057-212]